In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.metrics import mean_squared_error,r2_score

from sklearn.linear_model import LinearRegression

In [3]:
data=pd.read_excel('Concrete_data.xls')
data.head()

Cement (component 1)(kg in a m^3 mixture)  \
0                                      540.0   
1                                      540.0   
2                                      332.5   
3                                      332.5   
4                                      198.6   

   Blast Furnace Slag (component 2)(kg in a m^3 mixture)  \
0                                                0.0       
1                                                0.0       
2                                              142.5       
3                                              142.5       
4                                              132.4       

   Fly Ash (component 3)(kg in a m^3 mixture)  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   

   Water  (component 4)(kg in a m^3 mixture)  \
0                                      162.0   
1                                      162.0   
2                                      228.0   
3                                      228.0   
4                                      192.0   

   Superplasticizer (component 5)(kg in a m^3 mixture)  \
0                                                2.5     
1                                                2.5     
2                                                0.0     
3                                                0.0     
4                                                0.0     

   Coarse Aggregate  (component 6)(kg in a m^3 mixture)  \
0                                             1040.0      
1                                             1055.0      
2                                              932.0      
3                                              932.0      
4                                              978.4      

   Fine Aggregate (component 7)(kg in a m^3 mixture)  Age (day)  \
0                                              676.0         28   
1                                              676.0         28   
2                                              594.0        270   
3                                              594.0        365   
4                                              825.5        360   

   Concrete compressive strength(MPa, megapascals)   
0                                         79.986111  
1                                         61.887366  
2                                         40.269535  
3                                         41.052780  
4                                         44.296075

In [4]:
X=pd.DataFrame(data.drop(['Concrete compressive strength(MPa, megapascals) '],axis=1))

In [5]:
Y=pd.DataFrame(data['Concrete compressive strength(MPa, megapascals) '])

In [6]:
Y.head()

Concrete compressive strength(MPa, megapascals) 
0                                         79.986111
1                                         61.887366
2                                         40.269535
3                                         41.052780
4                                         44.296075

In [7]:
X=np.array(X)
Y=np.array(Y)

In [8]:
Y

array([[79.98611076],
       [61.88736576],
       [40.26953526],
       ...,
       [23.69660064],
       [32.76803638],
       [32.40123514]])

In [9]:
X

array([[ 540. ,    0. ,    0. , ..., 1040. ,  676. ,   28. ],
       [ 540. ,    0. ,    0. , ..., 1055. ,  676. ,   28. ],
       [ 332.5,  142.5,    0. , ...,  932. ,  594. ,  270. ],
       ...,
       [ 148.5,  139.4,  108.6, ...,  892.4,  780. ,   28. ],
       [ 159.1,  186.7,    0. , ...,  989.6,  788.9,   28. ],
       [ 260.9,  100.5,   78.3, ...,  864.5,  761.5,   28. ]])

In [10]:
scaler=MinMaxScaler()

In [11]:
x=scaler.fit_transform(X)
y=scaler.fit_transform(Y)

In [12]:
y

array([[0.9674449 ],
       [0.7419643 ],
       [0.47264169],
       ...,
       [0.26617018],
       [0.37918535],
       [0.37461561]])

In [13]:
x

array([[1.        , 0.        , 0.        , ..., 0.69476744, 0.20572002,
        0.07417582],
       [1.        , 0.        , 0.        , ..., 0.73837209, 0.20572002,
        0.07417582],
       [0.52625571, 0.39649416, 0.        , ..., 0.38081395, 0.        ,
        0.73901099],
       ...,
       [0.10616438, 0.38786867, 0.54272864, ..., 0.26569767, 0.46663322,
        0.07417582],
       [0.1303653 , 0.51947691, 0.        , ..., 0.54825581, 0.48896136,
        0.07417582],
       [0.36278539, 0.27963272, 0.39130435, ..., 0.18459302, 0.42022077,
        0.07417582]])

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [15]:
regressor=LinearRegression()

In [16]:
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [17]:
y_pred=regressor.predict(x_test)

In [18]:
y_pred

array([[0.35818908],
       [0.67915678],
       [0.43949112],
       [0.36174422],
       [0.13322019],
       [0.39683911],
       [0.28657732],
       [0.64966799],
       [0.26985361],
       [0.78916459],
       [0.43896184],
       [0.37602117],
       [0.46968905],
       [0.35917738],
       [0.17380058],
       [0.11591569],
       [0.25012908],
       [0.30873812],
       [0.31612908],
       [0.28991662],
       [0.38159156],
       [0.28645034],
       [0.26383861],
       [0.2473359 ],
       [0.75982269],
       [0.40478882],
       [0.57835594],
       [0.417676  ],
       [0.26280725],
       [0.68847188],
       [0.38433978],
       [0.63748935],
       [0.6047004 ],
       [0.53046729],
       [0.39205819],
       [0.49045781],
       [0.2925351 ],
       [0.40070773],
       [0.36511806],
       [0.43522856],
       [0.32493985],
       [0.39507812],
       [0.60742231],
       [0.15613658],
       [0.66411803],
       [0.43437723],
       [0.37047387],
       [0.517

In [19]:
for i in zip(y_pred,y_test):
    print(i)

(array([0.35818908]), array([0.28937965]))
(array([0.67915678]), array([0.67041179]))
(array([0.43949112]), array([0.35276332]))
(array([0.36174422]), array([0.43403941]))
(array([0.13322019]), array([0.03052793]))
(array([0.39683911]), array([0.38353176]))
(array([0.28657732]), array([0.35745331]))
(array([0.64966799]), array([0.38703637]))
(array([0.26985361]), array([0.18122627]))
(array([0.78916459]), array([0.74960917]))
(array([0.43896184]), array([0.45008504]))
(array([0.37602117]), array([0.43728633]))
(array([0.46968905]), array([0.43110172]))
(array([0.35917738]), array([0.28937106]))
(array([0.17380058]), array([0.07729904]))
(array([0.11591569]), array([0.05152124]))
(array([0.25012908]), array([0.2554416]))
(array([0.30873812]), array([0.34569396]))
(array([0.31612908]), array([0.304489]))
(array([0.28991662]), array([0.31556976]))
(array([0.38159156]), array([0.38310227]))
(array([0.28645034]), array([0.37267433]))
(array([0.26383861]), array([0.42491711]))
(array([0.2473

In [20]:
np.sqrt(mean_squared_error(y_test,y_pred))

0.13092860317725585

In [21]:
r2_score(y_test,y_pred)

0.6020954652306598